In [39]:
import numpy as np
import pandas as pd
from scipy.stats import norm as gaussian
import math

In [40]:
df = pd.read_csv('Sample input and output for HMM/Input/data.txt', header=None)
df.columns = ['rainfall']

In [41]:
df.head()

rainfall
0  104.524318
1   98.295391
2  101.201301
3   96.825882
4   99.777784

In [42]:
with open('Sample input and output for HMM/Input/data.txt') as f:
    rainfall = np.loadtxt(f)

In [43]:
with open('Sample input and output for HMM/Input/parameters.txt') as f:
    nstates = int(next(f))
    trans_mat = np.asarray([[float(x) for x in next(f).strip().split('\t')] for i in range(nstates)])
    mu = np.asarray([float(x) for x in next(f).strip().split('\t')])
    sigma = np.asarray([float(x) for x in next(f).strip().split('\t')])

In [44]:
emit_mat = np.asarray([[gaussian.pdf(x, loc=mu[i], scale=math.sqrt(sigma[i])) for x in rainfall] for i in range(nstates)]).T

In [53]:
def viterbi(obs, states, init_prob, trans_mat, emit_mat):
    prev_prob = np.log(init_prob * emit_mat[0]).reshape(1, -1)
    print(prev_prob)
    prev_st = np.full((1, states), -1)
    
    for ep in emit_mat[1:]:
#         print(np.log(trans_mat * ep))
        probs = prev_prob[-1].reshape(-1, 1) + np.log(trans_mat * ep)
#         print('probs:\n', probs)
        prev_prob = np.concatenate((prev_prob, probs.max(axis=0).reshape(1, -1)))
#         print('prev_prob:\n', prev_prob[-1])
        prev_st = np.concatenate((prev_st, probs.argmax(axis=0).reshape(1, -1)))
#         print('prev_st:\n', prev_st[-1])
    
    most_likely_st = np.array([prev_prob[-1].argmax()])
    for st in prev_st[:0:-1]:
        most_likely_st = np.append(most_likely_st, st[most_likely_st[-1]])
    
    st, counts = np.unique(most_likely_st, return_counts=True)
    
    print(st, counts)
    

In [54]:
init_prob = np.full(nstates, 1/nstates)
print('init_prob: ', init_prob)
viterbi(rainfall, nstates, init_prob, trans_mat, emit_mat)

init_prob:  [0.5 0.5]
[[-458.54367416   -3.78685078]]
[0 1] [291 709]


In [47]:
y = np.array([-1, 2])

In [48]:
trans_mat

array([[0.7, 0.3],
       [0.1, 0.9]])

In [49]:
emit_mat[0]

array([1.43893971e-199, 4.53337453e-002])

In [50]:
np.concatenate((np.array([[10, 20]]), np.array([[1, 2]])))[-1]

array([1, 2])

In [51]:
np.arange(10).argmax()

9